### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Rasalexman/KDispatcher#1]
1. Have the priority optional
2. Have function that will auto-register and un-register, using Lifecycle library:

https://developer.android.com/topic/libraries/architecture/lifecycle

**Comment by Rasalexman** [comment]
Hello @AndroidDeveloperLB 
Thanks for the feedback.
1) I have added priority as optional with the default value since version 0.1.6
2) I don't want to add another implementation libraries into this project cause I want that it will stay independent of AndroidSDK. Only Kotlin) That's why I used it in a backend too.
You can simply realize it by yourself ))) Cheers and stay tuned

**Comment by AndroidDeveloperLB** [comment]
1. I see. So please update the main page of this repository, as my request was based on what I see there. I wanted to look at the code, but saw only the sample project.
2. Too bad.
